- hosts: couchdb
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
          - gnupg2
          - curl
        update_cache: true

    - name: Install Caddy keyring
      shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg

    - name: Add apt sources for Caddy
      shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list

    - name: Install Caddy
      become: true
      apt:
        name: caddy
        state: present
        update_cache: true
